# Generated by Django 4.2.4 on 2023-08-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='NAME',
        ),
    ]
