# Generated by Django 4.2.4 on 2023-08-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_options_rename_name_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='NAME',
            new_name='name',
        ),
    ]
